### ISSUE TITLE
Nimbus dependency tree broken

### ISSUE THREAD

**Issue by KnyGoo** [e-Box-Enterprise-Belgium/examples#4]
Please add following to pom.xml:
`<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>nimbus-jose-jwt</artifactId>
    <version>5.14</version>
</dependency>`

Example not running because of new dependeny of nimbus-jose-jwt is included which is not backwards compatible.

**Comment by be-smals-thim** [comment]
Great thanks @KnyGoo indeed it was needed. I also upgraded the example for OauthV4 as OauthV3 is about to be deprecated. Just need to change URL and audience
